---
- name: Add nginx ppa repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install nginx
  apt: name=nginx state=installed update_cache=yes
  when: ppastable|success
  register: nginx_installed

- name: Ensure nginx is enabled and will start on boot
  service: name=nginx state=started enabled=yes
  when: nginx_installed|success

- name: Disable nginx default site
  file: path="/etc/nginx/sites-enabled/default" state=absent
  when: nginx_installed|success
  notify:
    - Restart nginx

- name: Configure nginx
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "{{ item.exp }}"
    line: "{{ item.line }}"
    backrefs: yes
    state: present
  with_items:
    - { exp: '^user www-data;', line: 'user vagrant;' }
    - { exp: '# server_names_hash_bucket_size 64;', line: 'server_names_hash_bucket_size 64;' }
  when: nginx_installed|success
  notify:
    - Restart nginx