---
- name: Setup vagrant
  hosts: all
  remote_user: vagrant
  become: true

  roles:
    - common
    - nginx
    - php
    - composer
    - postgresql
    - redis
    - mailhog
    - supervisor
    - beanstalkd
