---
- name: Add postgres repository apt-key
  apt_key: id='ACCC4CF8' url='https://www.postgresql.org/media/keys/ACCC4CF8.asc' state=present

- name: Add postgres repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' state=present
  register: ppastable

- name: Install postgres
  apt: name={{ item }} state=installed update_cache=yes
  when: ppastable|success
  with_items:
    - postgresql
    - libpq-dev # required for ansible postgres module
    - python-psycopg2 # required for ansible postgres module
  register: postgres_installed

- name: Ensure postgresql is enabled and will start on boot
  service: name=postgresql state=started enabled=yes
  when: postgres_installed|success

- name: Configure postgres listen address
  lineinfile:
    dest: /etc/postgresql/9.6/main/postgresql.conf
    regexp: '^#listen_addresses = *'
    line: "listen_addresses = '*'"
    backrefs: yes
    state: present
  when: postgres_installed|success
  notify:
    - Restart postgres

- name: Configure postgres allow access to host
  blockinfile:
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    insertafter: EOF
    block: 'host    all             all             192.168.0.0/16           md5'
    state: present
  when: postgres_installed|success
  notify:
    - Restart postgres

- name: Create db super user
  postgresql_user: name=root password=secret role_attr_flags=SUPERUSER state=present
  become_user: postgres
  when: postgres_installed|success